export const roomsData = [
  {
    slug: "chambre-standard-ch02",
    name: "Chambre Standard CH02",
    roomNumber: "CH02",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 1,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-ch05",
    name: "Chambre Standard CH05",
    roomNumber: "CH05",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 2,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-ch06",
    name: "Chambre Standard CH06",
    roomNumber: "CH06",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 3,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-ch08",
    name: "Chambre Standard CH08",
    roomNumber: "CH08",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 4,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-ch12",
    name: "Chambre Standard CH12",
    roomNumber: "CH12",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 5,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b01",
    name: "Chambre Standard B01",
    roomNumber: "B01",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 6,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b04",
    name: "Chambre Standard B04",
    roomNumber: "B04",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 7,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b05",
    name: "Chambre Standard B05",
    roomNumber: "B05",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 8,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b07",
    name: "Chambre Standard B07",
    roomNumber: "B07",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 9,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b10",
    name: "Chambre Standard B10",
    roomNumber: "B10",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 10,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-standard-b11",
    name: "Chambre Standard B11",
    roomNumber: "B11",
    shortDescription: "Chambre standard confortable avec bureau ergonomique, literie de qualité, salle de bain soignée, Wi-Fi gratuit, accès piscine et salle de sport.",
    description: "Notre établissement propose 11 chambres Standard, conçues pour allier confort et fonctionnalité. Leur superficie optimisée pour votre bien-être offre un espace agréable et harmonieux.\n\nChaque chambre est équipée d'un bureau avec assise ergonomique, d'une literie de qualité, ainsi que d'une salle de bain aménagée avec des matériaux soigneusement sélectionnés. Vous bénéficiez également d'un accès Wi-Fi gratuit, ainsi que de l'accès libre à la salle de sport et à la piscine.",
    basePrice: 58500,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 23,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 11,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "standard",
  },
  {
    slug: "chambre-confort-ch03",
    name: "Chambre Confort CH03",
    roomNumber: "CH03",
    shortDescription: "Chambre spacieuse au design moderne avec douche à l'italienne, literie d'exception, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Spacieuses et élégantes, nos chambres Confort portent parfaitement leur nom. Elles séduisent par leur design moderne et leur décoration subtile, pensée pour créer une atmosphère apaisante.\n\nVéritables espaces dédiés à votre bien-être, elles sont équipées d'une literie d'exception, d'une douche à l'italienne moderne, ainsi que d'un accès Wi-Fi gratuit. Vous profitez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 65000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 28,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Douche à l'italienne", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 12,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort",
  },
  {
    slug: "chambre-confort-ch11",
    name: "Chambre Confort CH11",
    roomNumber: "CH11",
    shortDescription: "Chambre spacieuse au design moderne avec douche à l'italienne, literie d'exception, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Spacieuses et élégantes, nos chambres Confort portent parfaitement leur nom. Elles séduisent par leur design moderne et leur décoration subtile, pensée pour créer une atmosphère apaisante.\n\nVéritables espaces dédiés à votre bien-être, elles sont équipées d'une literie d'exception, d'une douche à l'italienne moderne, ainsi que d'un accès Wi-Fi gratuit. Vous profitez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 65000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 28,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Douche à l'italienne", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 13,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort",
  },
  {
    slug: "chambre-confort-ch15",
    name: "Chambre Confort CH15",
    roomNumber: "CH15",
    shortDescription: "Chambre spacieuse au design moderne avec douche à l'italienne, literie d'exception, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Spacieuses et élégantes, nos chambres Confort portent parfaitement leur nom. Elles séduisent par leur design moderne et leur décoration subtile, pensée pour créer une atmosphère apaisante.\n\nVéritables espaces dédiés à votre bien-être, elles sont équipées d'une literie d'exception, d'une douche à l'italienne moderne, ainsi que d'un accès Wi-Fi gratuit. Vous profitez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 65000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 28,
    amenities: ["TV écran plat", "Chaînes câblées", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Bureau", "Douche à l'italienne", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 14,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort",
  },
  {
    slug: "chambre-confort-plus-b02",
    name: "Chambre Confort Plus B02",
    roomNumber: "B02",
    shortDescription: "Chambre spacieuse avec terrasse privative vue jardin, literie douillette, douche à l'italienne, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Les chambres Confort Plus ont été pensées pour rendre vos séjours encore plus agréables. Spacieuses et lumineuses, elles offrent un cadre idéal dédié à votre bien-être.\n\nElles se distinguent par leur terrasse privative avec vue sur notre jardin, parfaite pour profiter d'un moment de détente et respirer l'air pur.\n\nSoigneusement décorées, elles disposent d'une literie douillette, d'une douche à l'italienne équipée, ainsi que d'un accès Wi-Fi gratuit. Vous bénéficiez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 73000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 30,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse privative vue jardin", "Bureau", "Douche à l'italienne", "Kit de toilette", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 15,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort-plus",
  },
  {
    slug: "chambre-confort-plus-b03",
    name: "Chambre Confort Plus B03",
    roomNumber: "B03",
    shortDescription: "Chambre spacieuse avec terrasse privative vue jardin, literie douillette, douche à l'italienne, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Les chambres Confort Plus ont été pensées pour rendre vos séjours encore plus agréables. Spacieuses et lumineuses, elles offrent un cadre idéal dédié à votre bien-être.\n\nElles se distinguent par leur terrasse privative avec vue sur notre jardin, parfaite pour profiter d'un moment de détente et respirer l'air pur.\n\nSoigneusement décorées, elles disposent d'une literie douillette, d'une douche à l'italienne équipée, ainsi que d'un accès Wi-Fi gratuit. Vous bénéficiez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 73000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 30,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse privative vue jardin", "Bureau", "Douche à l'italienne", "Kit de toilette", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 16,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort-plus",
  },
  {
    slug: "chambre-confort-plus-b06",
    name: "Chambre Confort Plus B06",
    roomNumber: "B06",
    shortDescription: "Chambre spacieuse avec terrasse privative vue jardin, literie douillette, douche à l'italienne, Wi-Fi gratuit et accès piscine et salle de sport.",
    description: "Les chambres Confort Plus ont été pensées pour rendre vos séjours encore plus agréables. Spacieuses et lumineuses, elles offrent un cadre idéal dédié à votre bien-être.\n\nElles se distinguent par leur terrasse privative avec vue sur notre jardin, parfaite pour profiter d'un moment de détente et respirer l'air pur.\n\nSoigneusement décorées, elles disposent d'une literie douillette, d'une douche à l'italienne équipée, ainsi que d'un accès Wi-Fi gratuit. Vous bénéficiez également d'un accès libre à la salle de sport et à la piscine.",
    basePrice: 73000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 30,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse privative vue jardin", "Bureau", "Douche à l'italienne", "Kit de toilette", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 17,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "confort-plus",
  },
  {
    slug: "chambre-prestige-b08",
    name: "Chambre Prestige B08",
    roomNumber: "B08",
    shortDescription: "Chambre raffinée avec terrasse offrant une vue imprenable sur le jardin et la piscine, dans une atmosphère sobre et élégante.",
    description: "Nos chambres Prestige sont conçues pour vous offrir un séjour paisible, alliant confort et raffinement dans une atmosphère sobre et élégante.\n\nVéritable invitation à la détente, elles disposent d'une belle terrasse offrant une vue imprenable sur le jardin et la piscine, pour profiter pleinement de chaque instant en toute sérénité.",
    basePrice: 80000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 31,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse vue jardin et piscine", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 18,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "prestige-plus",
  },
  {
    slug: "chambre-prestige-b09",
    name: "Chambre Prestige B09",
    roomNumber: "B09",
    shortDescription: "Chambre raffinée avec terrasse offrant une vue imprenable sur le jardin et la piscine, dans une atmosphère sobre et élégante.",
    description: "Nos chambres Prestige sont conçues pour vous offrir un séjour paisible, alliant confort et raffinement dans une atmosphère sobre et élégante.\n\nVéritable invitation à la détente, elles disposent d'une belle terrasse offrant une vue imprenable sur le jardin et la piscine, pour profiter pleinement de chaque instant en toute sérénité.",
    basePrice: 80000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 31,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse vue jardin et piscine", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 19,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "prestige-plus",
  },
  {
    slug: "chambre-prestige-b12",
    name: "Chambre Prestige B12",
    roomNumber: "B12",
    shortDescription: "Chambre raffinée avec terrasse offrant une vue imprenable sur le jardin et la piscine, dans une atmosphère sobre et élégante.",
    description: "Nos chambres Prestige sont conçues pour vous offrir un séjour paisible, alliant confort et raffinement dans une atmosphère sobre et élégante.\n\nVéritable invitation à la détente, elles disposent d'une belle terrasse offrant une vue imprenable sur le jardin et la piscine, pour profiter pleinement de chaque instant en toute sérénité.",
    basePrice: 80000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 31,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Terrasse vue jardin et piscine", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 20,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "prestige-plus",
  },
  {
    slug: "chambre-prestige-plus-ch14",
    name: "Chambre Prestige Plus CH14",
    roomNumber: "CH14",
    shortDescription: "Chambre généreuse avec double terrasse vue jardin, piscine et plage, literie haut de gamme et salle de bain spacieuse.",
    description: "La chambre Prestige Plus, aux espaces généreux, est conçue pour vous offrir un séjour paisible, alliant confort et élégante sobriété. Un équilibre parfait pour savourer chaque instant en toute tranquillité.\n\nElle se distingue par sa double terrasse offrant une vue imprenable sur le jardin, la piscine et la plage, pour une expérience d'exception en toute intimité.\n\nVous y trouverez une literie haut de gamme, une salle de bain spacieuse, ainsi qu'un accès Wi-Fi gratuit. L'accès à la salle de sport et à la piscine est également inclus.",
    basePrice: 86000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 44,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Double terrasse vue jardin, piscine et plage", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 21,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "prestige-plus",
  },
  {
    slug: "suite-nuptiale-ch16",
    name: "Suite Nuptiale CH16",
    roomNumber: "CH16",
    shortDescription: "Suite unique avec lit rond sur mesure, décoration épurée et grande terrasse arrondie offrant une vue panoramique sur le jardin, la piscine et la mer.",
    description: "Nous vous proposons plusieurs suites, dont notre suite nuptiale, spécialement conçue pour célébrer l'amour dans toute sa splendeur.\n\nUnique en son genre, elle se distingue par son lit rond sur mesure et sa décoration épurée, à la fois chic et contemporaine. Chaque détail a été pensé pour vous offrir un cadre intime et raffiné, idéal pour une nuit de noces inoubliable.\n\nSa grande terrasse arrondie dévoile une vue panoramique sur le jardin, la piscine et la mer, pour un moment hors du temps.",
    basePrice: 100000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 44,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Grande terrasse arrondie vue panoramique (jardin, piscine, mer)", "Coffre fort", "Sèche cheveux", "Pèse personne", "Dressing", "Peignoires (x2)", "Chaussons (x2)", "Salle de bain privative", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Machine à café Nespresso", "Bureau", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: true,
    order: 22,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "suite-nuptiale",
  },
  {
    slug: "petite-mezzanine-ch10",
    name: "Petite Mezzanine CH10",
    roomNumber: "CH10",
    shortDescription: "Espace familial avec salon et chambre en hauteur, décoration afro-contemporaine, balcon vue jardin. Jusqu'à 4 personnes. 2 petits déjeuners offerts.",
    description: "Parce que vos séjours en famille méritent un cadre adapté, nous avons imaginé des chambres en mezzanine, alliant espace et convivialité.\n\nComposées d'un salon et d'une chambre en hauteur, elles peuvent accueillir jusqu'à 4 personnes, offrant ainsi une solution idéale pour les familles.\n\nElles disposent d'une salle de bain privative avec douche à l'italienne, d'un balcon ainsi que d'une agréable vue sur le jardin.\n\nLeur décoration associe subtilement inspirations africaines et design contemporain, pour créer une atmosphère unique et chaleureuse.",
    basePrice: 100000,
    currency: "XOF",
    maxGuests: 4,
    beds: 2,
    bathrooms: 1,
    sizeSqm: 71,
    amenities: ["2 petits déjeuners offerts", "Canapé lit dépliable", "TV (x2)", "Climatiseur (x2)", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille (x2)", "Thé", "Café", "Sucre", "Mini bar", "Balcon vue jardin", "Coffre fort", "Machine à café Nespresso", "Salle de bain privative", "Douche à l'italienne", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Bureau"],
    isPublished: true,
    isFeatured: false,
    order: 23,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "petite-mezzanine",
  },
  {
    slug: "grande-mezzanine-ch07",
    name: "Grande Mezzanine CH07",
    roomNumber: "CH07",
    shortDescription: "Grande mezzanine familiale avec salon et chambre en hauteur, décoration afro-contemporaine, balcon vue jardin. Jusqu'à 6 personnes. 2 petits déjeuners offerts.",
    description: "Pensées pour vos séjours en famille, nos grandes mezzanines sont composées d'un salon et d'une chambre en hauteur. Elles peuvent accueillir jusqu'à 6 personnes, offrant un cadre idéal pour partager des moments conviviaux et privilégiés.\n\nElles disposent d'une salle de bain privative avec douche à l'italienne, d'un balcon ainsi que d'une agréable vue sur le jardin.\n\nLeur décoration associe avec élégance des inspirations africaines à un style contemporain, pour une atmosphère chaleureuse et unique.",
    basePrice: 115000,
    currency: "XOF",
    maxGuests: 6,
    beds: 2,
    bathrooms: 1,
    sizeSqm: 71,
    amenities: ["2 petits déjeuners offerts", "Canapé lit dépliable", "TV (x2)", "Climatiseur (x2)", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille (x2)", "Thé", "Café", "Sucre", "Mini bar", "Balcon vue jardin", "Coffre fort", "Machine à café Nespresso", "Salle de bain privative", "Douche à l'italienne", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Bureau"],
    isPublished: true,
    isFeatured: false,
    order: 24,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "grande-mezzanine",
  },
  {
    slug: "grande-mezzanine-ch09",
    name: "Grande Mezzanine CH09",
    roomNumber: "CH09",
    shortDescription: "Grande mezzanine familiale avec salon et chambre en hauteur, décoration afro-contemporaine, balcon vue jardin. Jusqu'à 6 personnes. 2 petits déjeuners offerts.",
    description: "Pensées pour vos séjours en famille, nos grandes mezzanines sont composées d'un salon et d'une chambre en hauteur. Elles peuvent accueillir jusqu'à 6 personnes, offrant un cadre idéal pour partager des moments conviviaux et privilégiés.\n\nElles disposent d'une salle de bain privative avec douche à l'italienne, d'un balcon ainsi que d'une agréable vue sur le jardin.\n\nLeur décoration associe avec élégance des inspirations africaines à un style contemporain, pour une atmosphère chaleureuse et unique.",
    basePrice: 115000,
    currency: "XOF",
    maxGuests: 6,
    beds: 2,
    bathrooms: 1,
    sizeSqm: 71,
    amenities: ["2 petits déjeuners offerts", "Canapé lit dépliable", "TV (x2)", "Climatiseur (x2)", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille (x2)", "Thé", "Café", "Sucre", "Mini bar", "Balcon vue jardin", "Coffre fort", "Machine à café Nespresso", "Salle de bain privative", "Douche à l'italienne", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Bureau"],
    isPublished: true,
    isFeatured: false,
    order: 25,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "grande-mezzanine",
  },
  {
    slug: "mini-suite-senior-ch04",
    name: "Mini Suite Senior CH04",
    roomNumber: "CH04",
    shortDescription: "Suite junior chic de 35 m² avec salon séparé, terrasse vue jardin et 2 petits déjeuners offerts. Capacité 2 personnes.",
    description: "Notre Suite Junior, à la fois confortable et élégante, a été pensée pour offrir des conditions idéales de bien-être. D'une superficie de 35 m², elle dispose d'un agréable espace de vie avec un salon séparé de la chambre.\n\nSa terrasse offre une vue imprenable sur le jardin, pour un moment de détente privilégié.\n\nElle peut accueillir jusqu'à 2 personnes et comprend deux petits-déjeuners offerts.",
    basePrice: 125000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 35,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Grande terrasse vue jardin", "Coffre fort", "Sèche cheveux", "Pèse personne", "Peignoires (x2)", "Machine à café Nespresso", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "2 petits déjeuners offerts", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: false,
    order: 26,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "mini-suite-senior",
  },
  {
    slug: "mini-suite-superieure-b14",
    name: "Mini Suite Supérieure B14",
    roomNumber: "B14",
    shortDescription: "Suite de 63 m² avec décoration minimaliste, lit king size, dressing, double douche jacuzzi + italienne, grande terrasse vue jardin. 2 petits déjeuners offerts.",
    description: "Notre Mini Suite Supérieure vous accueille dans un cadre spacieux et aéré, à la décoration minimaliste et contemporaine, propice à la tranquillité.\n\nD'une superficie de 63 m², elle dispose d'un salon, d'un plateau de courtoisie, d'un lit king size, d'un dressing ainsi que d'une double douche.\n\nConçue pour accueillir jusqu'à 2 personnes, elle inclut deux petits-déjeuners offerts.\n\nSituée à l'étage, sa grande terrasse offre une agréable vue sur la verdure de notre jardin, pour un séjour placé sous le signe de la détente.",
    basePrice: 155000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 63,
    amenities: ["TV écran plat", "Climatiseur", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Grande terrasse vue jardin (1er étage)", "Coffre fort", "Sèche cheveux", "Pèse personne", "Peignoires (x2)", "Machine à café Nespresso", "Double douche (jacuzzi + italienne)", "Dressing", "Bureau", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "2 petits déjeuners offerts", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: true,
    order: 27,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "mini-suite-superieure",
  },
  {
    slug: "suite-presidentielle-ch01",
    name: "Suite Présidentielle CH01",
    roomNumber: "CH01",
    shortDescription: "Suite d'exception de 80 m² avec grand salon, salle à manger, dressing, salle de bain privative et double terrasse vue jardin.",
    description: "Découvrez l'excellence du confort avec la Suite Présidentielle de l'Hôtel Nahoui. Véritable écrin de prestige, elle s'étend sur 80 m² et offre des volumes généreux, pensés pour un séjour d'exception.\n\nElle se compose d'un élégant salon avec espace salle à manger, harmonieusement séparé de la chambre et du dressing, garantissant intimité et raffinement.\n\nAlliance subtile de matières nobles, de contrastes maîtrisés et de teintes douces, l'atmosphère y est résolument apaisante, propice à une détente absolue.\n\nBaignée de lumière naturelle, la suite s'ouvre sur une double terrasse offrant une vue imprenable sur le jardin, pour savourer pleinement chaque instant dans un cadre exclusif.",
    basePrice: 225000,
    currency: "XOF",
    maxGuests: 2,
    beds: 1,
    bathrooms: 1,
    sizeSqm: 80,
    amenities: ["Grand salon avec salle à manger séparé", "TV (x2)", "Climatiseur (x2)", "Dressing", "Salle de bain privative", "Wi-Fi gratuit", "Bouilloire", "Eau en bouteille", "Thé", "Café", "Sucre", "Mini bar", "Double terrasse vue jardin", "Coffre fort", "Sèche cheveux", "Pèse personne", "Peignoires (x2)", "Machine à café Nespresso", "Kit de toilette (chapeau de bain, peigne, rasoir, brosse à dent)", "Accès salle de sport", "Accès piscine"],
    isPublished: true,
    isFeatured: true,
    order: 28,
    checkInStart: "15:00",
    checkInEnd: "22:00",
    checkOutTime: "11:00",
    checkInMethod: "Arrivée autonome avec clavier",
    cancellationPolicy: "Annulation gratuite avant 7 jours, 50% de remboursement avant 3 jours",
    roomTypeSlug: "suite-presidentielle",
  },
];
